# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonym',
            field=models.BooleanField(default=False),
        ),
    ]
