# Generated by Django 4.2.6 on 2023-10-17 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_checktest_test_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 12, 24, 16, 884014, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
