# Generated by Django 4.2.6 on 2023-10-19 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 11, 53, 31, 116213, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
