# Generated by Django 4.2.6 on 2024-02-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_test_end_date_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 14, 49, 30, 962640, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
