# Generated by Django 4.2.6 on 2025-04-20 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_test_end_date_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 7, 54, 33, 535386, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
